---
- name: Apply system updates
  hosts: all
  become: yes
  vars:
    reboot: false  # set to true to reboot automatically if updates require it
  tasks:
    - name: Update packages on Debian/Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Update packages on RedHat/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Check if reboot is required on Debian/Ubuntu
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check if reboot is required on RedHat/CentOS
      command: needs-restarting -r
      register: reboot_required_cmd
      changed_when: false
      failed_when: false
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Determine if reboot is needed
      set_fact:
        reboot_required: >-
          {{ reboot_required_file.stat.exists | default(false) or
             (reboot_required_cmd.rc == 1) | default(false) }}

    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible after updates"
        connect_timeout: 5
        reboot_timeout: 600
      when:
        - reboot
        - reboot_required
